declare interface Window { }
declare interface Event { }
declare interface Location { }
declare interface Date { }
declare interface Element { }
declare interface Document { }
declare interface Window { }
declare interface RegExp { }
declare interface HTMLElement { }
declare interface Node { }